services:

  mysql:
    image: mysql:8.0
    container_name: afyaflow-mysql 
    environment:
      MYSQL_ROOT_PASSWORD: james1421
      MYSQL_DATABASE: database_afyaflow
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  afyaflow-backend:
    build: ./AfyaFlow-Backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/database_afyaflow?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: james1421
      APPLICATION_SECURITY_JWT_SECRET_KEY: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      APPLICATION_SECURITY_JWT_EXPIRATION: 86400000

  afyaflow-frontend:
    build: ./AfyaFlow-Frontend
    ports:
      - "5173:80"
    depends_on:
      - afyaflow-backend

  afyaflow-staff:
    build: ./afyaflow-react
    ports:
      - "5174:80"
    depends_on:
      - afyaflow-backend
